hailapp/_core/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('dashboard.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hailapp/dashboard/urls.py
from django.conf.urls import url
from .views import MapView, SendClaimView, OpenClaimsView, \
                   CompletedClaimsView, AdjustersView, CreateAdjusterView, \
                   AdjusterProfileView, AdjusterProfileUpdateView, UpdateClaimsView, \
                   AdjusterDelete, login_view

from rest_framework.authtoken import views
from api.views import LocationUpdate, ClaimsAPI, PushIDUpdateAPI, UpdateClaimAPIView, \
                      ClaimFieldsAPI, ClaimFieldPhotoAPI

urlpatterns = [

    url(r'^accounts/login/$', login_view, name='login'),

	### VIEWS

    url(r'^$', MapView.as_view(), name='map'),
    url(r'^claims/send/$', SendClaimView.as_view(), name='send_claim'),
    url(r'^claims/open/$', OpenClaimsView.as_view(), name='open_claims'),
    url(r'^claims/completed/$', CompletedClaimsView.as_view(),
                                                    name='completed_claims'),
    url(r'^claims/update/(?P<pk>\d+)/$', UpdateClaimsView.as_view(), name='update_claim'),

    url(r'^adjusters/list$', AdjustersView.as_view(), name='adjusters'),
    url(r'^adjusters/profile/(?P<pk>\d+)/$', AdjusterProfileView.as_view(), name='show_adjuster'),
    url(r'^adjusters/profile/(?P<pk>\d+)/update/$', AdjusterProfileUpdateView.as_view(), name='update_adjuster'),
    url(r'^adjusters/new/$', CreateAdjusterView.as_view(),
                                                    name='create_adjuster'),
    url(r'^adjusters/delete/(?P<pk>\d+)/$', AdjusterDelete.as_view(),
                                                    name='delete_adjuster'),

    ### API

    url(r'^api/token-auth$', views.obtain_auth_token),
    url(r'^api/claims$', ClaimsAPI.as_view()),
    url(r'^api/claims/update/(?P<pk>\d+)$', UpdateClaimAPIView.as_view()),
    url(r'^api/pushid_update$', PushIDUpdateAPI.as_view()),
    url(r'^api/location-update$', LocationUpdate.as_view()),

    url(r'^api/claimfields/(?P<pk>\d+)$', ClaimFieldsAPI.as_view(), name='claim_fields'),
    url(r'^api/claimfields/(?P<pk>\d+)/photo/upload$', ClaimFieldPhotoAPI.as_view()),
]

hailapp/dashboard/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.db.models.signals import post_save, pre_save, post_delete
from django.dispatch import receiver

from rest_framework.authtoken.models import Token

COUNTRIES = (
    ('canada', 'Canada'),
)

CLAIM_STATES = (
    ('started', 'started'),
    ('assigned', 'assigned'),
    ('completed', 'completed')
)

FIELD_TYPES = (
    ('cereals', 'Cereals'),
    ('oilseeds', 'Oilseeds'),
    ('pulses', 'Pulses'),
)

class Adjuster(models.Model):
    user = models.OneToOneField(User, blank=True, null=True)
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    phone = models.CharField(max_length=20, blank=True)
    email = models.EmailField()
    photo = models.ImageField(upload_to='adjusters', blank=True,
                        default='person-placeholder.png')
    lat = models.CharField(max_length=20, blank=True)
    lng = models.CharField(max_length=20, blank=True)

    def __unicode__(self):
        return "{} {}".format(self.first_name, self.last_name)

    @property
    def full_name(self):
        return "{} {}".format(self.first_name, self.last_name)



class Claim(models.Model):
    # Meta
    created = models.DateTimeField(auto_now_add=True)
    assigned_adjuster = models.ForeignKey(Adjuster, null=True, blank=True)

    # Client information
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    addr_street_1 = models.CharField(max_length=50)
    addr_street_2 = models.CharField(max_length=50, blank=True)
    city = models.CharField(max_length=50)
    postal_code = models.CharField(max_length=50, blank=True)
    phone = models.CharField(max_length=50)

    # Loss information
    policy_no = models.CharField(max_length=50)
    loss_no = models.CharField(max_length=50, blank=True)
    date_of_loss = models.DateField(null=True, blank=True)
    state = models.CharField(max_length=100, default='started', choices=CLAIM_STATES)


    def __unicode__(self):
        return "{} {}".format(self.first_name, self.last_name)

    class Meta:
        ordering = ['created']

    @property
    def assigned(self):
        aa = self.assigned_adjuster
        if not aa:
            return "No assignment"
        else:
            return aa


class ClaimField(models.Model):
    claim = models.ForeignKey(Claim)
    type = models.CharField(max_length=50, choices=FIELD_TYPES)
    name = models.CharField(max_length=50, blank=True)
    acres = models.IntegerField()
    quarter = models.CharField(max_length=20, blank=True)
    section = models.CharField(max_length=20, blank=True)
    township = models.CharField(max_length=20, blank=True)
    range = models.CharField(max_length=20, blank=True)
    meridian = models.CharField(max_length=20, blank=True)
    loss = models.DecimalField(default=0.0, max_digits=6, decimal_places=2)
    completed = models.BooleanField(default=False)
    photo = models.ImageField(upload_to='fields', blank=True, null=True)

@receiver(post_save, sender=User)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)

@receiver(post_delete, sender=Adjuster)
def ensure_profile_exists(sender, instance, **kwargs):
    user = instance.user
    user.is_active = False
    user.save()

hailapp/dashboard/forms.py
from django import forms
from .models import Adjuster, Claim, ClaimField
from django.contrib.auth.models import User


class NewAdjusterForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput)

	class Meta:
		model = Adjuster
		fields = ['first_name', 'last_name', 'phone', 'email', 'photo', 'password']

	def save(self, commit=True):
		adjuster = super(NewAdjusterForm, self).save(commit=False)
		u, crt = User.objects.get_or_create(username=self.cleaned_data['email'])
		u.set_password(self.cleaned_data['password'])
		u.is_active = True
		u.save()
		adjuster.user = u
		adjuster.save()
		return adjuster


class ClaimForm(forms.ModelForm):

	class Meta:
		model = Claim
		fields = ['first_name', 'last_name', 'addr_street_1', 'addr_street_1', 'addr_street_2', 
				  'city', 'postal_code', 'phone', 'policy_no', 'loss_no', 'date_of_loss', 
				  'assigned_adjuster']

	def __init__(self, *args, **kwargs):
		form = super(ClaimForm, self).__init__(*args, **kwargs)
		for visible in self.visible_fields():
			visible.field.widget.attrs['class'] = 'form-control'


class FieldForm(forms.ModelForm):
	class Meta:
		model = ClaimField
		fields = ['type', 'acres', 'quarter', 'section', 'township', 'range', 'meridian']

	def __init__(self, *args, **kwargs):
		form = super(FieldForm, self).__init__(*args, **kwargs)
		for visible in self.visible_fields():
			visible.field.widget.attrs['class'] = 'form-control'

hailapp/dashboard/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.shortcuts import render, get_object_or_404
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.decorators import login_required
from .models import Adjuster, Claim, ClaimField
from django.utils.decorators import method_decorator
from .forms import NewAdjusterForm, ClaimForm, FieldForm
from django.contrib.auth import authenticate, login
from push_notifications.models import APNSDevice


@method_decorator(login_required, name='dispatch')
class MapView(TemplateView):
    template_name = 'dashboard/map.html'

    def get_context_data(self, *args, **kwargs):
        context = super(MapView, self).get_context_data(*args, **kwargs)
        context['adjusters'] = Adjuster.objects.all()
        return context


@method_decorator(login_required, name='dispatch')
class SendClaimView(CreateView):
    model = Claim
    form_class = ClaimForm
    success_url = reverse_lazy('open_claims')

    def get_context_data(self, *args, **kwargs):
        context = super(SendClaimView, self).get_context_data(*args, **kwargs)
        context['field_form'] = FieldForm
        return context

    def form_valid(self, form):
        response = super(SendClaimView, self).form_valid(form)

        post = self.request.POST

        for i, x in enumerate(post.getlist('type')):
            if x != '':
                type = post.getlist('type')[i]
                acres = post.getlist('acres')[i]
                quarter = post.getlist('quarter')[i]
                section = post.getlist('section')[i]
                township = post.getlist('township')[i]
                range = post.getlist('range')[i]
                meridian = post.getlist('meridian')[i]

                ClaimField.objects.create(claim=self.object,
                                          type=type,
                                          acres=acres,
                                          quarter=quarter,
                                          section=section,
                                          township=township,
                                          range=range,
                                          meridian=meridian)

        try:
            user = self.object.assigned_adjuster.user
            registered_apns = APNSDevice.objects.filter(user=user)

            for apns in registered_apns:
                apns.send_message("New claim available!")
        except:
            pass

        return response


@method_decorator(login_required, name='dispatch')
class OpenClaimsView(TemplateView):
    template_name = 'dashboard/open_claims.html'

    def post(self, request, *args, **kwargs):
        adj_id = request.POST.get('adjuster')
        claim_id = request.POST.get('claim-id-send')
        print(adj_id)
        if adj_id:
            claim = get_object_or_404(Claim, pk=claim_id)
            if adj_id == "---":
                claim.assigned_adjuster = None
            else:
                adjuster = get_object_or_404(Adjuster, pk=adj_id)
                claim.assigned_adjuster = adjuster
            claim.save()

        return HttpResponseRedirect(reverse_lazy('open_claims'))

    def get_context_data(self, *args, **kwargs):
        context = super(OpenClaimsView, self).get_context_data(*args, **kwargs)
        context['claims'] = Claim.objects.filter(state__in=['assigned', 'started'])
        context['adjusters'] = Adjuster.objects.all()
        return context


@method_decorator(login_required, name='dispatch')
class CompletedClaimsView(TemplateView):
    template_name = 'dashboard/completed_claims.html'
    def get_context_data(self, *args, **kwargs):
        context = super(CompletedClaimsView, self).get_context_data(*args, **kwargs)
        context['claims'] = Claim.objects.filter(state='completed')
        return context


@method_decorator(login_required, name='dispatch')
class AdjustersView(TemplateView):
    template_name = 'dashboard/adjusters.html'

    def get_context_data(self, *args, **kwargs):
        context = super(AdjustersView, self).get_context_data(*args, **kwargs)
        context['adjusters'] = Adjuster.objects.all()
        return context


@method_decorator(login_required, name='dispatch')
class CreateAdjusterView(CreateView):
    model = Adjuster
    success_url = reverse_lazy('adjusters')
    form_class = NewAdjusterForm


@method_decorator(login_required, name='dispatch')
class AdjusterProfileView(DetailView):
    model = Adjuster


@method_decorator(login_required, name='dispatch')
class AdjusterProfileUpdateView(UpdateView):
    model = Adjuster
    fields = ['first_name', 'last_name', 'phone', 'email', 'photo']
    success_url = reverse_lazy('adjusters')


@method_decorator(login_required, name='dispatch')
class UpdateClaimsView(TemplateView):
    template_name = 'dashboard/update_claims.html'

    def get_context_data(self, pk, *args, **kwargs):
        context = super(UpdateClaimsView, self).get_context_data(*args, **kwargs)
        claim = Claim.objects.get(pk=pk)
        context['form'] = ClaimForm(instance=claim)
        context['field_forms'] = []

        for f in claim.claimfield_set.all():
            context['field_forms'].append(FieldForm(instance=f))

        return context

    def post(self, request, *args, **kwargs):
        instance = Claim.objects.get(pk=kwargs['pk'])
        form = ClaimForm(request.POST, instance=instance)
        if form.is_valid():
            obj = form.save()
            post = request.POST
            fields = instance.claimfield_set.all()
            fields.delete()

            for i, x in enumerate(post.getlist('type')):
                type = post.getlist('type')[i]
                acres = post.getlist('acres')[i]
                quarter = post.getlist('quarter')[i]
                section = post.getlist('section')[i]
                township = post.getlist('township')[i]
                range = post.getlist('range')[i]
                meridian = post.getlist('meridian')[i]

                ClaimField.objects.create(claim=obj,
                                          type=type,
                                          acres=acres,
                                          quarter=quarter,
                                          section=section,
                                          township=township,
                                          range=range,
                                          meridian=meridian)
        if request.GET.get('completed', None):
            return HttpResponseRedirect(reverse_lazy('completed_claims'))
        else:
            return HttpResponseRedirect(reverse_lazy('open_claims'))

@method_decorator(login_required, name='dispatch')
class AdjusterDelete(DeleteView):
    model = Adjuster
    success_url = reverse_lazy('adjusters')


def login_view(request):
    if request.method == 'GET':
        return render(request, 'dashboard/login.html')

    username = request.POST.get('username')
    password = request.POST.get('password')
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        return HttpResponseRedirect(reverse_lazy('map'))
    else:
        return HttpResponseRedirect("{}?invalid".format(reverse_lazy('login'),))

hailapp/dashboard/templates/dashboard/adjuster_confirm_delete.html
{% extends 'dashboard/base.html' %}
{% load bootstrap_forms %}

{% block content %}
<div class="container">
	<h4>Are you sure you want to delete adjuster {{ object.full_name }}?</h4>
	<p></p>
	<form method="POST">
	{% csrf_token %}
	<input class="btn btn-danger" type="submit" value="Delete" />
	<a class="btn btn-primary" href="{% url 'show_adjuster' object.pk %}">Cancel</a>
</div>
{% endblock content %}

hailapp/dashboard/templates/dashboard/adjuster_detail.html
{% extends 'dashboard/base.html' %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-xs-12">
			<br />
			<a href="{% url 'update_adjuster' object.pk %}" class="btn btn-sm btn-primary">Update profile</a>
			<a href="{% url 'delete_adjuster' object.pk %}" class="btn btn-sm btn-danger">Delete profile</a>
		</div>
	</div>
	<div class="row">
		<div class="adjuster-profile col-xs-12">
			<img class="photo" src="{{ object.photo.url }}" />
			<div class="details">
				<p class="name">{{ object.first_name }} {{ object.last_name }}</p>
				<p class="phone">Phone: {{ object.phone }}</p>
				<p class="email">E-mail: {{ object.email }}</p>
			</div>
		</div>
	</div>
</div>
<p>
{% endblock content %}

hailapp/dashboard/templates/dashboard/adjuster_form.html
{% extends 'dashboard/base.html' %}
{% load bootstrap_forms %}

{% block content %}
<div class="container">
	<form action="" method="post">
	  {% csrf_token %}
	    {{ form|as_bootstrap }}
	    <input type="submit" value="Save" class="btn btn-primary"/>
	    <a href="{% url 'adjusters' %}" class="btn btn-danger">Cancel</a>
	</form>
</div>
{% endblock content %}

hailapp/dashboard/templates/dashboard/adjusters.html
{% extends 'dashboard/base.html' %}
{% load static %}

{% block extendhead %}
<link rel="stylesheet" type="text/css" href="{% static 'dashboard/css/adjusters.css' %}" />
{% endblock extendhead %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h1>
        Adjusters <small><a id="create_adjuster_btn" class="btn btn-primary btn-sm" href="{% url 'create_adjuster' %}"><i class="fa fa-user-plus" aria-hidden="true"></i> Create new</a></small>
      </h1>
    </div>
  </div>
  {% for adjuster in adjusters %}
  <div class="row">
    <div class="adjuster-wrapper col-xs-12">
      <div class="adjuster">
        <div class="photo">
          <img src="{{ adjuster.photo.url }}" />
        </div>
        <div class="details">
          <p class="name">{{ adjuster.first_name }} {{ adjuster.last_name }}</p>
          <p class="phone"><i class="fa fa-phone-square" aria-hidden="true"></i> {{ adjuster.phone }}</p>
          <p class="email"><i class="fa fa-envelope-o" aria-hidden="true"></i> {{ adjuster.email }}</p>
          <p class="claims"><i class="fa fa-file" aria-hidden="true"></i> Claims:
          {% for claim in adjuster.claim_set.all %}
            <a href="#claim_details">{{ claim.policy_no }}
          {% empty %}
            No assigned claims.
          {% endfor %}
          </p>
          <a href="{% url 'show_adjuster' adjuster.pk %}" class="btn btn-primary btn-sm btn-block">Show profile</a>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}

hailapp/dashboard/templates/dashboard/claim_form.html
{% extends 'dashboard/base.html' %}
{% load bootstrap_forms static %}

{% block extendhead %}
<link rel="stylesheet" href="{% static 'dashboard/css/bootstrap-datepicker.standalone.css' %}" type="text/css" />
{% endblock extendhead %}

{% block content %}
<div class="container">
	<form action="" method="post">
	{% csrf_token %}
		<div class="row">
			<div class="col-sm-6">
				{% if form.errors %}
				    {% for field in form %}
				        {% for error in field.errors %}
				            <div class="alert alert-danger">
				                <strong>{{ error|escape }}</strong>
				            </div>
				        {% endfor %}
				    {% endfor %}
				    {% for error in form.non_field_errors %}
				        <div class="alert alert-danger">
				            <strong>{{ error|escape }}</strong>
				        </div>
				    {% endfor %}
				{% endif %}
				<h3>Client info</h3>
				<label for="first_name">First name</label>
				{{ form.first_name }}
				<label for="last_name">Last name</label>
				{{ form.last_name }}
				<label for="phone">Phone</label>
				{{ form.phone }}
				<label for="addr_street_1">Address 1</label>
				{{ form.addr_street_1 }}
				<label for="addr_street_2">Address 2</label>
				{{ form.addr_street_2 }}
				<label for="city">City</label>
				{{ form.city }}
				<label for="postal_code">Postal code</label>
				{{ form.postal_code }}

				<h3>Claim info</h3>
				<label for="policy_no">Policy no.</label>
				{{ form.policy_no }}
				<label for="loss_no">Loss no.</label>
				{{ form.loss_no }}
				<label for="date_of_loss">Date of loss</label>
				{{ form.date_of_loss }}

				<h3><small>Adjuster(s):</small></h3>
				{{ form.assigned_adjuster }}
				<input id="submit_claim" type="submit" value="SUBMIT FORM" class="btn btn-primary"/>
			</div>
			<div class="col-sm-6">
				<h3>Damaged Fields</h3>
					<div id="fields-container" >

						<div class="field_fields">
							<div class="close_field_form">X</div>
							<label for="crop_type">Crop type</label>
							{{ field_form.type }}
							<br/>
							<div class="container-fluid">
								<div class="row">
									<div class="col-sm-6 smfield">
										<label for="acres">Acres</label>
										{{ field_form.acres }}
									</div>
									<div class="col-sm-6 smfield">
										<label for="quarter">Quarter</label>
										{{ field_form.quarter }}
									</div>
									<div class="col-sm-6 smfield">
										<label for="section">Section</label>
										{{ field_form.section }}
									</div>
									<div class="col-sm-6 smfield">
										<label for="township">Township</label>
										{{ field_form.township }}
									</div>
									<div class="col-sm-6 smfield">
										<label for="range_">Range</label>
										{{ field_form.range }}
									</div>
									<div class="col-sm-6 smfield">
										<label for="meridian">Meridian</label>
										{{ field_form.meridian }}
									</div>
								</div>
							</div>
					</div>
				</div>
				<input id="new_field_btn" type="button" value="Add new field" class="btn btn-primary"/>
			</div>
		</div>
	</form>
</div>
{% endblock content %}

{% block extendfoot %}
<script src="{% static 'dashboard/js/bootstrap-datepicker.js' %}"></script>
<script type="text/javascript">

$(document).ready(function () {

	$('#id_date_of_loss').datepicker({
		format: "yyyy-mm-dd"
	});

	$(".close_field_form").on('click', function() {
		$(this).parent().remove();
	});

	var fields_form = $('.field_fields').clone()
	$("#new_field_btn").on('click', function() {
		f = fields_form.clone()
		$("#fields-container").append(f);

		f.find(".close_field_form").on('click', function() {
			$(this).parent().remove();
		});

	});

});
</script>
{% endblock extendfoot %}

hailapp/dashboard/templates/dashboard/login.html
{% extends 'dashboard/base.html' %}
{% load bootstrap_forms %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-sm-6">
			{% if request.GET.invalid %}
				Invalid user.
			{% endif %}
			<div class="well">
			<form method="POST">
				{% csrf_token %}
				<div class="form-group">
					<label for="username">Username</label>
					<input class="form-control" type="text" name="username" />
				</div>
				<div class="form-group">
					<label for="password">Password</label>
					<input class="form-control" type="password" name="password" />
				</div>
				
				<input type="submit" value="Login" class="btn btn-primary" />
			</form>
			</div>
		</div>
	</div>
</div>
{% endblock content %}

hailapp/dashboard/templates/dashboard/send_claim.html
{% extends 'dashboard/base.html' %}
{% load bootstrap_forms %}

{% block content %}
<div class="container">
	<h2>Send claim</h2>
	<form action="" method="post">
	  {% csrf_token %}
	    {{ form|as_bootstrap }}
	    <input type="submit" value="Save" class="btn btn-primary"/>
	</form>
</div>
{% endblock content %}

{% block extendfoot %}
<script src="{% static 'dashboard/js/bootstrap-datepicker.js' %}"></script>
<script>
$('#id_date_of_loss').datepicker();
</script>
{% endblock extendfoot %}

hailapp/dashboard/templates/dashboard/update_claims.html
{% extends 'dashboard/base.html' %}

{% load static %}

{% block extendhead %}
<link rel="stylesheet" href="{% static 'dashboard/css/bootstrap-datepicker.standalone.css' %}" type="text/css" />
{% endblock extendhead %}

{% block content %}
<div class="container">
	<form action="" method="post">
	{% csrf_token %}
		<div class="row">
			<div class="col-sm-6">
				{% if form.errors %}
				    {% for field in form %}
				        {% for error in field.errors %}
				            <div class="alert alert-danger">
				                <strong>{{ error|escape }}</strong>
				            </div>
				        {% endfor %}
				    {% endfor %}
				    {% for error in form.non_field_errors %}
				        <div class="alert alert-danger">
				            <strong>{{ error|escape }}</strong>
				        </div>
				    {% endfor %}
				{% endif %}
				<h3>Client info</h3>
				<label for="first_name">First name</label>
				{{ form.first_name }}
				<label for="last_name">Last name</label>
				{{ form.last_name }}
				<label for="phone">Phone</label>
				{{ form.phone }}
				<label for="addr_street_1">Address 1</label>
				{{ form.addr_street_1 }}
				<label for="addr_street_2">Address 2</label>
				{{ form.addr_street_2 }}
				<label for="city">City</label>
				{{ form.city }}
				<label for="postal_code">Postal code</label>
				{{ form.postal_code }}

				<h3>Claim info</h3>
				<label for="policy_no">Policy no.</label>
				{{ form.policy_no }}
				<label for="loss_no">Loss no.</label>
				{{ form.loss_no }}
				<label for="date_of_loss">Date of loss</label>
				{{ form.date_of_loss }}

				<h3><small>Adjuster(s):</small></h3>
				{{ form.assigned_adjuster }}
				<input id="submit_claim" type="submit" value="Update claim" class="btn btn-primary"/>
			</div>
			<div class="col-sm-6">
				<h3>Damaged Fields</h3>
				<div id="fields-container" >
					{% for field_form in field_forms %}
					<div class="field_fields">
						<label for="crop_type">Crop type</label>
						{{ field_form.type }}
						<br/>
						<div class="container-fluid">
							<div class="row">
								<div class="col-sm-6 smfield">
									<label for="acres">Acres</label>
									{{ field_form.acres }}
								</div>
								<div class="col-sm-6 smfield">
									<label for="quarter">Quarter</label>
									{{ field_form.quarter }}
								</div>
								<div class="col-sm-6 smfield">
									<label for="section">Section</label>
									{{ field_form.section }}
								</div>
								<div class="col-sm-6 smfield">
									<label for="township">Township</label>
									{{ field_form.township }}
								</div>
								<div class="col-sm-6 smfield">
									<label for="range_">Range</label>
									{{ field_form.range }}
								</div>
								<div class="col-sm-6 smfield">
									<label for="meridian">Meridian</label>
									{{ field_form.meridian }}
								</div>
							</div>
						</div>
					</div>
					{% endfor %}
				</div>
			</div>
			<div class="col-sm-6">

			</div>
			<div class="col-sm-12">
			</div>
		</div>
	</form>
</div>
{% endblock %}

{% block extendfoot %}
<script src="{% static 'dashboard/js/bootstrap-datepicker.js' %}"></script>
<script type="text/javascript">

$(document).ready(function () {

	$('#id_date_of_loss').datepicker({
		format: "yyyy-mm-dd"
	});

	var fields_form = $('.field_fields').clone()
	$("#new_field_btn").on('click', function() {
		f = fields_form.clone()
		$("#fields-container").append(f);
	});

});
</script>
{% endblock extendfoot %}